### ISSUE TITLE
Install only necessary build dependencies

### ISSUE THREAD

**Issue by iEgit** [exogen/postinstall-build#11]
I'm working on a library and the following problem has been arised. Here is an example of my `package.json` chunk.

```json
"devDependencies": {
  "es5-shim": "^4.5.2",
  "inkiik-docstrap": "^1.1.1",
  "jscs": "^2.9.0",
  "jsdoc": "^3.4.0",
  "jshint": "^2.9.1",
  "karma": "^0.13.19",
  "karma-mocha": "^0.2.1",
  "karma-phantomjs-launcher": "^1.0.0",
  "karma-sinon-chai": "^1.1.0",
  "mocha": "^2.4.5",
  "phantomjs-prebuilt": "^2.1.3",
  "webpack": "^1.12.12"
},
```

The problem is that for my library to build it only requires webpack to be installed. But unfortunately all other libraries are installed as well and the installation time lasts way longer than it should be. Maybe devDependencies is not the right place to look for the *build* dependecies in some cases. I suggest we could utilize some other section where only build dependecies would be explicitly declared. Here is an example.
```json
devDependencies: {
  "mocha": "^2.4.5",
  "webpack": "^1.12.12"
},
buildDependencies: ['webpack', 'babel']
```

So if `build` field is present in `package.json` - install only what's listed there.

**Comment by wtgtybhertgeghgtwtg** [comment]
`buildDependencies` is not a valid field for `package.json`.

**Comment by exogen** [comment]
Some thoughts on this:

- I like the custom `package.json` field over the `package.build.json` approach taken in #12. Custom fields are totally allowed and it's super common for modern build tools to do it this way ... Babel, AVA, Istanbul, `pre-commit`, `standard` all use a custom `package.json` field.

- I think we should anticipate more configuration being specified there (like all the existing CLI flags, possibly), so it should be an object like:
  ```json
  {
    "postinstallBuild": {
      "dependencies": ["webpack"]
    }
  }
  ```
  (`postinstallBuild` or `postinstall-build`? The question haunts me.)

**Comment by louisgv** [comment]
I have been investigating this issue for a while, and I think it's reasonable to just have a `buildDependencies` field just like so:

```
{
  "devDependencies": {  },
  "scripts": { },
  "dependencies": { },
  "buildDependencies": { }
}
```

Instead of a nested giant object. If anticipating giant object, I'd suggest having the user move it to a file i.e `.postinstallrc`similar to `.babelrc` or `.eslintrc` instead.

Hopefully this can be merged into npm and resolve https://github.com/npm/npm/issues/13876 as well...

The first use of `buildDependencies` I have seen is from https://github.com/tgriesser/bookshelf/blob/master/package.json and it seems to serve the purpose.

**Comment by exogen** [comment]
PR for this in #20 if you'd like to test it out! Installing `exogen/postinstall-build#install-build-dependencies` will get you the version from that branch.
