### ISSUE TITLE
Question: Postinstall on module

### ISSUE THREAD

**Issue by khankuan** [exogen/postinstall-build#13]
Hi, I understand that postinstall runs when installing module A in module B. However, it is also running when I do `npm install` in module A while development. Is there a way to only execute when it is being installed elsewhere? Thanks!

**Comment by exogen** [comment]
Hi @khankuan! I have a PR #14 with this feature; if you'd like to test it out before I release it, you can install the branch like so:

```sh
npm install exogen/postinstall-build#only-as-dependency-flag-execpath
```

and your `postinstall-build` command will magically get the new `--only-as-dependency` flag :)
