### ISSUE TITLE
`npm prune --production` breaks Continuous Integration

### ISSUE THREAD

**Issue by dcrockwell** [exogen/postinstall-build#3]
`npm prune --production` should be optional, because dev dependencies can be needed by automated testing systems, etc.

**Comment by dcrockwell** [comment]
Sorry, it was a misunderstanding and bug in my build. Nothing wrong here.

**Comment by dcrockwell** [comment]
Actually it is a problem with the `npm prune` call. Reopening.

**Comment by dcrockwell** [comment]
Workaround:

In your `.travis.yml` file:

``` yml
before_script:
  - npm install
```

**Comment by exogen** [comment]
heya @dcrockwell, if you're still seeing this/needing a workaround, could you post a demo repo that exhibits this issue? I'm curious.

**Comment by exogen** [comment]
Ah I think I understand when this would be a problem – when you're doing no-arguments `npm install` of a project itself for testing or development. In that case we expect to have the `devDependencies` around afterward, so `npm prune` should be skipped.

I'm inclined to actually make the entire `postinstall-build` command a no-op in the no-arguments `npm install` case, but that might be more unexpected.
