### ISSUE TITLE
can't run on windows

### ISSUE THREAD

**Issue by eben0** [exogen/postinstall-build#8]
my package.json has the following scripts:

```
"scripts": {
    "clean": "rm -rf build",
    "cleanall": "rm -rf build && rm -rf node_modules",
    "compile": "babel lib --out-dir build",
    "install": "postinstall-build build 'npm run compile'"
  },
```

When I call npm install, windows cannot find npm, I added it to PATH environment.
When I call "C:\Windows\system32\cmd.exe /d /s /c npm" it works fine.

Errors:

```
''npm' is not recognized as an internal or external command,
operable program or batch file.
{ Error: Command failed: C:\Windows\system32\cmd.exe /d /s /c 'npm

    at ChildProcess.<anonymous> (C:\Jobs\***\workspace\node_modules\postinstall-build\index.js:47:13)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /d /s /c \'npm' }
```

WORKAROUND:

use double qoutes
`"install": "postinstall-build build \"npm run compile\""`

**Comment by exogen** [comment]
That's interesting, do you know of any potential workaround `postinstall-build` itself could implement? Hopefully I won't have to add a caveat for Windows users to use double quotes – but I wonder if they already need to for other scripts and such without `postinstall-build`?

**Comment by eben0** [comment]
The problem is, I think, how process.argv works on Windows:

[ 'C:\Program Files\nodejs\node.exe',
  'C:\Users\***\node_modules\postinstall-build\index.js',
  'build',
  '\'npm',
  'run',
  'compile\'' ]
